[versions]
agp = "8.13.0"
assertk = "0.28.1"
desugar_jdk_libs = "2.1.5"
kotlin = "2.2.0"
coreKtx = "1.15.0"
junit = "4.13.2"
extJunit = "1.2.1"
kotlinxCoroutinesTest = "1.8.0"
xmlUtil = "0.91.2"
timber = "5.0.1"
koin = "3.5.3"
retrofit2 = "2.11.0"
okHttp = "4.12.0"
dokka = "1.9.20"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
compose-bom = "2025.03.00"
navigation = "2.8.9"
serialization = "1.7.0"
accompanistPermission = "0.37.0"
accompanistSystemUi = "0.36.0"
playServices = "21.3.0"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit2" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
xmlUtilCore = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlUtil" }
xml-test = { module = "io.github.pdvrieze.xmlutil:core-jdk", version.ref = "xmlUtil" }
xmlUtilSerialization = { module = "io.github.pdvrieze.xmlutil:serialization-jvm", version.ref = "xmlUtil" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttpLogger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
dokka = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "dokka" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
compose-icons = { group="androidx.compose.material", name = "material-icons-extended" }
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
accompanist-permission = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermission" }
accompanist-system-ui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemUi" }
play-services = { module = "com.google.android.gms:play-services-location", version.ref = "playServices" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }